# Prompts to record (example)

prompts = [
    "The quick brown fox jumps over the lazy dog.",
    "She sells seashells down by the seashore.",
    "Peter Piper picked a peck of pickled peppers.",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    "I'll be there at nine thirty in the morning.",
    "Call me at zero one two, three four five, six seven eight nine.",
    "Today is Thursday; the date is October third, two thousand twenty-five.",
    "The appointment is scheduled for 11:45 AM on 2025 dash 10 dash 15.",
    "Please email the report to ronak@example.com by E O D.",
    "The URL is https colon slash slash example dot com slash docs.",
    "Machine learning models require data, compute, and iteration.",
    "He whispered a secret so softly I could barely hear it.",
    "Wow — that's incredible! I can't believe it.",
    "Why did you leave the door unlocked?",
    "The baby laughed and clapped when the dog barked.",
    "Electricity flows from higher potential to lower potential.",
    "In nineteen ninety-nine, many people expected the world to end.",
    "She bought three apples, a banana, and a dozen oranges.",
    "The conference begins at nine, but registration opens at eight fifteen.",
    "I prefer coffee in the morning, tea in the afternoon, and water at night.",
    "Can you book a table for four at the Indian restaurant nearby?",
    "The temperature rose by two point five degrees after noon.",
    "Next week we'll ship the prototype to San Francisco.",
    "This is a long sentence to help train prosody, where I'll pause, take a breath, and then continue with a different cadence.",
    "He read the instructions carefully; nevertheless, he missed the first step.",
    "There's a comma in the middle, and—sometimes—dashes too.",
    "The word data can be pronounced DAY-ta or DAH-ta.",
    "We use APIs, SDKs, and CLIs to integrate services.",
    "NATO spells it N A T O, while HTTP is H T T P.",
    "A rolling stone gathers no moss, yet it creates a smooth rhythm when read aloud.",
    "Will you be attending the party, or will you stay home?",
    "The cat sat on the mat, staring at the curtains intently.",
    "I told her, Meet me by the blue door, but she arrived late.",
    "Eleven plus eleven equals twenty-two.",
    "My address is twenty one B, Baker Street, near the old clock tower.",
    "The quick fix often causes long-term technical debt; plan properly.",
    "She asked, Do you really think that will work? and he replied, Yes.",
    "The algorithm converged after forty-seven iterations.",
    "Can you say the months January through December in one breath?",
    "He spoke slowly, emphasizing the final syllables dramatically.",
    "A noisy, crowded room can make it hard to enunciate clearly.",
    "The louder the music, the less likely you'll hear subtle consonants.",
    "The contractor will arrive between eight and ten tomorrow morning.",
    "This is a neutral sentence. Read it flat.",
    "Read this sentence with excitement and a smile.",
    "Read this sentence angrily, with short clipped words.",
    "My bank account ends in one two three four; I keep the rest private.",
    "The serial number is A1B2 dash C3D4 dash E5F6.",
    "The lake reflected the mountains like a mirror at sunrise.",
    "Finish this paragraph with a long, calming exhale and a gentle cadence.",
]
