import logging
import re

logger = logging.getLogger(__name__)


def normalize_sql(sql: str, dialect: str) -> str:
    """
    Normalize an SQL query to be dialect-agnostic.

    This function normalizes an SQL query to be dialect-agnostic, by
    applying dialect-specific rules to the query. These rules
    include:

    - Collapsing whitespace and removing trailing semicolons
    - Replacing dialect-specific keywords and phrases
    - Replacing dialect-specific data types

    The function takes an SQL query and a dialect as input, and returns
    the normalized query.

    Supported dialects are sqlite, postgresql, mysql, and mariadb.

    :param sql: The SQL query to normalize
    :type sql: str
    :param dialect: The dialect of the SQL query
    :type dialect: str
    :return: The normalized SQL query
    :rtype: str
    """
    sql = sql.strip()

    # --- Universal cleanup ---
    sql = re.sub(r"\s+", " ", sql)  # collapse whitespace
    # sql = sql.replace(";", "").strip()  # drop trailing semicolon for safety

    # --- Normalize schema behavior ---
    if dialect == "sqlite":
        # SQLite does not support schema-qualified names (schema.table)
        sql = re.sub(r"\b[a-zA-Z_][a-zA-Z0-9_]*\.", "", sql)
        sql = sql.replace("SERIAL", "INTEGER")
        sql = sql.replace("BIGSERIAL", "INTEGER")
        sql = sql.replace("BOOLEAN", "INTEGER")
        sql = re.sub(r"\bTRUE\b", "1", sql, flags=re.IGNORECASE)
        sql = re.sub(r"\bFALSE\b", "0", sql, flags=re.IGNORECASE)
        sql = re.sub(r"\bNOW\(\)", "CURRENT_TIMESTAMP", sql, flags=re.IGNORECASE)

    elif dialect == "postgresql":
        sql = re.sub(r"`([^`]*)`", r'"\1"', sql)  # backtick → double quote
        sql = sql.replace("AUTOINCREMENT", "GENERATED BY DEFAULT AS IDENTITY")
        sql = re.sub(r"\bCURRENT_TIMESTAMP\(\)", "CURRENT_TIMESTAMP", sql)
        sql = re.sub(r"\b1\s*=\s*1\b", "TRUE", sql)

    elif dialect in ("mysql", "mariadb"):
        sql = re.sub(r'"([^"]*)"', r"`\1`", sql)  # double quote → backtick
        sql = sql.replace("AUTOINCREMENT", "AUTO_INCREMENT")
        sql = sql.replace("SERIAL", "BIGINT AUTO_INCREMENT")
        sql = re.sub(r"\bCURRENT_TIMESTAMP\b(?!\()", "CURRENT_TIMESTAMP()", sql)
        sql = re.sub(r"\bTRUE\b", "1", sql, flags=re.IGNORECASE)
        sql = re.sub(r"\bFALSE\b", "0", sql, flags=re.IGNORECASE)

    else:
        logger.warning(f"No normalization rules defined for dialect '{dialect}'")

    if dialect == "sqlite":
        # Remove RETURNING clause, not supported before SQLite 3.35
        sql = re.sub(r"\bRETURNING\s+[\w,\s\*]+", "", sql, flags=re.IGNORECASE)
        # Replace CURRENT_TIMESTAMP() calls
        sql = sql.replace("CURRENT_TIMESTAMP()", "CURRENT_TIMESTAMP")

    # Add semicolon back for readability
    # sql = sql.strip() + ";"

    logger.debug(f"Normalized SQL for {dialect}:\n{sql}")
    return sql
