# holistiq/core/crypto/engine.py

import base64

from ..secure.algorithms import (
    aes_gcm_decrypt,
    aes_gcm_encrypt,
    base62_encode,
    hmac_sha256,
)
from .key_manager import (
    derive_key_from_password,
    validate_raw_key,
)

SALT_SIZE = 16

# ---------- High-level helpers ----------


def canonicalize_identifier(value: str) -> str:
    """
    Normalize an identifier string by stripping whitespace and converting to lowercase.

    Args:
        value: The identifier string to be normalized.

    Returns:
        The normalized identifier string.
    """
    return value.strip().lower()


def hmac_token(
    key: bytes,
    label: str,
    payload: str,
    length: int = 22,
) -> str:
    """
    Generate a URL-safe HMAC token based on a secret key and a label/payload pair.

    The token is constructed by concatenating the label and payload with a "||" separator,
    computing the HMAC-SHA256 digest of the resulting string, and then encoding the
    digest as a URL-safe base62 string. The resulting token is truncated to the
    specified length.

    Args:
        key: A secret key used for generating the token.
        label: A label string that will be concatenated with the payload.
        payload: A payload string that will be concatenated with the label.
        length: The desired length of the generated token.

    Returns:
        A URL-safe HMAC token as a string.
    """
    msg = f"{label}||{payload}".encode("utf-8")
    digest = hmac_sha256(key, msg)
    return base62_encode(digest)[:length]


# ---------- Password-based encryption ----------


def encrypt_with_password(plaintext: str, password: str) -> str:
    """
    Encrypt a plaintext string using a password.

    This function derives a key and salt from the given password using PBKDF2,
    encrypts the plaintext string using AES-GCM, and then encodes the
    resulting ciphertext along with the salt using URL-safe base64.

    Args:
        plaintext: The plaintext string to be encrypted.
        password: The password string used for key derivation.

    Returns:
        A URL-safe base64-encoded ciphertext string.
    """
    key, salt = derive_key_from_password(password)
    token = aes_gcm_encrypt(plaintext.encode("utf-8"), key)
    combined = salt + token
    return base64.urlsafe_b64encode(combined).decode("ascii")


def decrypt_with_password(token_b64: str, password: str) -> str:
    """
    Decrypt a ciphertext string generated by encrypt_with_password using a password.

    This function takes a URL-safe base64-encoded ciphertext string and a
    password string, derives a key and salt from the given password using
    PBKDF2, decrypts the ciphertext using AES-GCM, and then returns the
    resulting plaintext string.

    Args:
        token_b64: A URL-safe base64-encoded ciphertext string.
        password: The password string used for key derivation.

    Returns:
        The decrypted plaintext string.

    Raises:
        ValueError: If the given token is invalid or corrupted.
    """
    combined = base64.urlsafe_b64decode(token_b64.encode("ascii"))

    if len(combined) < SALT_SIZE + 13:
        raise ValueError("Invalid or corrupted token")

    salt = combined[:SALT_SIZE]
    token_with_nonce = combined[SALT_SIZE:]

    key, _ = derive_key_from_password(password, salt=salt)
    plaintext = aes_gcm_decrypt(token_with_nonce, key)
    return plaintext.decode("utf-8")


# ---------- Raw-key encryption ----------


def encrypt_with_raw_key(plaintext: str, key: bytes) -> str:
    """
    Encrypt a plaintext string using a raw encryption key.

    This function takes a plaintext string and a raw encryption key, validates the
    key, encrypts the plaintext string using AES-GCM, and then encodes the resulting
    ciphertext using URL-safe base64.

    Args:
        plaintext: The plaintext string to be encrypted.
        key: The raw encryption key used for encryption.

    Returns:
        A URL-safe base64-encoded ciphertext string.
    """
    validate_raw_key(key)
    token = aes_gcm_encrypt(plaintext.encode("utf-8"), key)
    return base64.urlsafe_b64encode(token).decode("ascii")


def decrypt_with_raw_key(token_b64: str, key: bytes) -> str:
    """
    Decrypt a ciphertext string using a raw encryption key.

    This function takes a ciphertext string and a raw encryption key, validates the
    key, decrypts the ciphertext string using AES-GCM, and then decodes the resulting
    plaintext string from bytes to UTF-8.

    Args:
        token_b64: The ciphertext string to be decrypted, encoded using URL-safe base64.
        key: The raw encryption key used for decryption.

    Returns:
        The decrypted plaintext string as a UTF-8 string.
    """
    validate_raw_key(key)
    token = base64.urlsafe_b64decode(token_b64.encode("ascii"))
    plaintext = aes_gcm_decrypt(token, key)
    return plaintext.decode("utf-8")
